# Generated by Django 4.2.16 on 2024-09-26 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="pub_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
